export const LEGACY_2025_TEAM = [
  { name: "Enzo Chaabnia", role: "President" },
  { name: "Oumaima Boucekkine", role: "Vice President" },
  { name: "Berbaoui Ashref Abderrahmane", role: "Vice President" },
  { name: "Leena IKHLEF", role: "Secretary General" },
  { name: "Dorsaf Messaoudi", role: "Relex department" },
  { name: "Maissa Lakel", role: "Relex department" },
  { name: "Khoumari Aya", role: "Co-Manager in Relex" },
  { name: "Mouhsine Abdelhakim Alouit", role: "Finance & Legal department" },
  { name: "Benzergua Djihene Chaimaa", role: "Finance & Legal Manager" },
  { name: "HACENE Serine Nour el Imane", role: "Finance & Legal Manager" },
  { name: "Youcef Belaib", role: "Co-manager Finance" },
  { name: "Takoua", role: "Co-design manager" },
  { name: "Maria Ines Raheb", role: "Design Co-manager" },
  { name: "Sara BENALI", role: "Design Co-manager" },
  { name: "BEKHEDDA Asma", role: "Co-ManagerDesign" },
  { name: "AMEZIANE Yani", role: "IT Manager" },
  { name: "Zineb Bouchaib", role: "Media & Marketing" },
  { name: "AHSATAL Imed Eddine", role: "Media & Marketing" },
  { name: "DJOUBANI Sarah", role: "Marketing Co-Manager" },
  { name: "Oussama Bouzaine", role: "HR" },
  { name: "Salah Badreddin", role: "HR Manager" },
  { name: "Sanna toutah", role: "Logistic Department" },
  { name: "Maroua Bouzira", role: "Events and logistics" },
  { name: "Mouhoun Cilia", role: "Events Logistics Co-manager" },
  { name: "Tazgart Kaouther", role: "Event Co-manager" },
  { name: "Wissal Oulem", role: "Project Manager" },
  { name: "BOULEFAA Mustapha", role: "Events Co-manager" }
];
